#defaults:
#  - dataset: hex-clustering

name: reddit
output_dir: outputs


feature_type: continuous

# N_runs for CSWR
n_samples : 20
max_size  : 256
sampling_method: CSWR

val_prop: 50 # If integer gives total size of validation set - heavy on gpu!
test_prop: 0.1
n_epochs : 50000
batch_size : 36
use_discriminator: True
vis_every: 1000
val_every  : 1000

model : dgd
depth : 5
n_layers : 2
hidden_dim : 512
extra_features: cycles

# Beta values are 10**{value} in code
min_beta: -4
max_beta: -2.5
min_beta_sampling: -5.5
max_beta_sampling: -2
diffusion_steps: 2000
diffusion_steps_sampling: 1000
distribution_weighting: 1.
add_noise_in_sampling: True

hidden_mlp_dims: {'X': 32, 'E': 32, 'y': 32}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 32, 'de': 32, 'dy': 32, 'n_head': 4, 'dim_ffX': 32, 'dim_ffE': 32, 'dim_ffy': 32}
