#defaults:
#  - dataset: hex-clustering

name: reddit
output_dir: outputs


feature_type: continuous
n_samples : 1024
max_size  : 48
val_prop: 0.025
test_prop: 0.1
n_epochs : 5000
batch_size : 36
val_every  : 500

n_layers : 5
hidden_dim : 256
extra_features: cycles

# Beta values are 10**{value} in code
min_beta: -6
max_beta: -2
min_beta_sampling: -4
max_beta_sampling: -2
diffusion_steps: 2000
diffusion_steps_sampling: 1000
distribution_weighting: 1.
add_noise_in_sampling: True

